language: shell

os:
  - linux
  - windows
  - osx
arch:
  - amd64
  - arm64
env:
  - IMPLEMENTATION_NAME=tdlib
  - IMPLEMENTATION_NAME=tdlight
osx_image: xcode11.3
dist: xenial
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - chmod +x travis/build.sh
  - chmod +x travis/build_success.sh
  - chmod +x travis/deploy.sh
  - chmod +x travis/install_dependencies.sh
  - chmod +x travis/setup_variables.sh
addons:
  apt:
    update: true
    packages:
    - make
    - git
    - zlib1g-dev
    - libssl-dev
    - gperf
    - cmake
    - g++
    - clang
    - libc++-dev
    - ccache
    - maven
    - python3
    - python3-pip
    - php7.0-cli
    - openjdk-8-jdk
cache:
  bundler: true
  cocoapods: true
  ccache: true
  directories:
    - ".autoconf"
    - "$HOME/.m2"
    - "$HOME/.ccache"
  
#deploy:
#  - provider: pages
#    skip-cleanup: true
#    github-token: $GITHUB_TOKEN
#    keep-history: false
#    local-dir: out/docs
#    repo: tdlight-team/tdlight-docs
#    target_branch: master
#    email: andrea@cavallium.it
#    name: "Andrea Cavalli"
#    verbose: true
#    on:
#      branch: dev
#      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_CPU_ARCH = amd64

install: ./travis/install_dependencies.sh
script: ./travis/build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then ./travis/build_success.sh; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./travis/deploy.sh; fi
