# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-integration

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    chmod +x travis/*.sh
    sudo apt-get update -y
    sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang-10 libc++-10-dev libc++abi-10-dev ccache maven python3 python3-pip php7.2-cli openjdk-11-jdk
  displayName: 'Pre installation'

- script: |
    sudo ./travis/install_dependencies.sh
  displayName: 'Install deps'

- script: |
    sudo ./travis/build.sh
  displayName: 'Build'

