# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-integration


strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

variables:
  AZURE_OS_NAME: $(Agent.OS)

steps:
- script: |
    uname -a 
    chmod +x azure/*.sh
  displayName: 'Pre installation'

- script: |
    ./azure/install_dependencies.sh
  displayName: 'Install deps'
  env:
    AZURE_OS_NAME: $(Agent.OS)

- script: |
    sudo ./azure/build.sh
  displayName: 'Build'
  env:
    AZURE_OS_NAME: $(Agent.OS)

