# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-integration


strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

variables:
  AZURE_OS_NAME: $(Agent.OS)
  AZURE_OS_ARCH: $(Agent.OSArchitecture)

steps:
- script: |
    uname -a 
    chmod +x azure/*.sh
  displayName: 'Pre installation'

- task: Bash@3
  inputs:
    targetType: 'filePath'
    filePath: './azure/install_dependencies.sh'
  displayName: 'Install deps'

- script: |
    ./azure/build.sh
  displayName: 'Build'

